import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header1 from "./components/headers/header1";
import Header2 from "./components/headers/header2";
import Footer from "./components/footer/footer";
import Breadcrumb from "./components/breadcrumb/breadcrumb";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Cheap Custom Packaging",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header1 />
        <Header2 />
        <Breadcrumb />
        {children}
        <Footer />
      </body>
    </html>
  );
}
